openapi: 3.0.0
info:
  title: Simple Calc API
  description: This is a simple Calc API
  contact:
    email: ericryanbowser@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/ericryanbowser/Calc_API/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://app.swaggerhub.com/apis/ericryanbowser/Calc_API/1.0.0#/
  description: SwaggerHub API Auto Mocking
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /add:
    post:
      summary: adds two numbers
      description: Adds two operands and returns the result
      operationId: add
      requestBody:
        description: Adds numbers
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operands'
      responses:
        "200":
          description: added numbers succeded
        "400":
          description: "invalid input, object invalid"
        "500":
          description: server error
  /sub:
    post:
      summary: Subtracts first number from the second
      description: Subtracts two numbers
      operationId: Sub
      requestBody:
        description: Subtracts numbers
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operands'
      responses:
        "200":
          description: Numbers reduced!
        "400":
          description: "invalid input, object invalid"
        "500":
          description: server error
  /mult:
    post:
      summary: Multiplies operands
      description: multiplies two numbers
      operationId: mult
      requestBody:
        description: Multiplies numbers
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operands'
      responses:
        "200":
          description: Numbers timesed!
        "400":
          description: "invalid input, object invalid"
        "500":
          description: server error
  /div:
    post:
      summary: Divides operands
      description: divides two numbers
      operationId: div
      requestBody:
        description: Divides numbers
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operands'
      responses:
        "200":
          description: Numbers div!
        "400":
          description: "invalid input, object invalid"
        "500":
          description: server error
components:
  schemas:
    Operands:
      required:
      - leftOperand
      - rightOperand
      type: object
      properties:
        leftOperand:
          type: number
          example: 1
        rightOperand:
          type: number
          example: 48030
